language: c
sudo: false

addons:
  apt:
    packages: &apt_packages
      - ghc-ppa-tools
      - alex-3.1.7
      - happy-1.19.5

matrix:
  include:
    - compiler: "ghc-8.2.1"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-8.2.1], sources: [hvr-ghc]}}
    - compiler: "ghc-8.0.2"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-8.0.2], sources: [hvr-ghc]}}
    - compiler: "ghc-7.10.3"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.10.3], sources: [hvr-ghc]}}
    - compiler: "ghc-7.8.4"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.8.4], sources: [hvr-ghc]}}
    - compiler: "ghc-7.8.4"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=head
      compiler: ": #GHC head"
      addons: {apt: {packages: [*apt_packages,cabal-install-2.0,ghc-head], sources: [hvr-ghc]}}

  allow_failures:
   - env: CABALVER=2.0 GHCVER=head

before_install:
  - unset CC
  - export HAPPYVER=1.19.5
  - export ALEXVER=3.1.7
  - export PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH

  - happy --version
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update

script:
  - make test-all # calls build, test package

notifications:
  email:
    - suhailshergill@gmail.com
  on_success: change
  on_failure: always
